---
title: "Midterm 3"
author: "Luke Letizia"
date: "April 18, 2018"
output: html_document
---


```{r, echo = FALSE, results = 'hide'}
Data = read.csv("C:/Users/Luke\\Downloads/STOCKPRICES.csv")
dates=as.Date(Data[,1],origin="1899-12-30")
```

###Question #1
```{r, echo = FALSE, results = 'hide'}
y=Data$APPLE
TT=length(y)
r1=acf(y)$acf[2]
beta1=r1
beta0=mean(y)*(1-r1)
beta0
beta1

##since |b1| < 1, the process is stationary.

arima(y,order=c(1,0,0))

yhat=c()
yhat[1]=y[1]
for(i in 2:TT){
  yhat[i]=beta0 + beta1*y[i-1]
}
yhat[1:10]
##These are the predicted y_hat values found using the predicted b0 and b1 values.

plot(dates,Data$APPLE, col="blue", cex=1.5, main="Apple Stock", xlab="Time")
```

```{r, echo = FALSE, results = 'hide'}
E=(y-yhat)
s=sqrt(sum(E^2)/(TT-3))

l=100
y_forecast=c()
y_forecast[1]=y[TT];
for(i in 2:(l+1)){
  y_forecast[i]=beta0+beta1*y_forecast[i-1]
}
ss=s*sqrt(cumsum(beta1^(2*(0:(l-1)))))
LB= c(y[TT], y_forecast[2:(l+1)]-2*ss)
UB=c(y[TT], y_forecast[2:(l+1)]+2*ss)

plot(1:TT, y, xlim=c(0,550), ylim=c(0, 200), xlab = "Time", ylab = "Price Per Share", main = "Forecasted Predicted Values")
points(TT:(TT+l),y_forecast, col="red")

lines((TT):(TT+l), LB)
lines((TT):(TT+l), UB)
```


```{r, echo = FALSE, results = 'hide'}
y=Data$APPLE
TT=length(y)
plot(y)
l=1
plot(y[1:(TT-l)], y[(1+l):TT])
cor(y[1:(TT-l)], y[(1+l):TT])

AC=acf(y,type=c("correlation"))
AC[1:10]
```

###Question #2
```{r, echo = FALSE, results = 'hide'}
Xij=c(101, 153, 52, 17, 14, 3, 4,1, 99, 121, 76, 32, 10, 3, 1, 110, 182, 80, 20, 21, 2, 160, 197, 82, 38, 19, 161, 254, 85, 46, 185, 201, 86, 178,261, 168)
xl=c(1,1,1,1,1,1,1,1,2,2,2,2,2,2,2, 3,3,3,3,3,3, 4,4,4,4,4, 5,5,5,5, 6,6,6,7,7, 8 )
yl=c(0, 1,2,3,4,5,6,7, 0,1,2,3,4,5,6,0,1,2,3,4,5,0,1,2,3,4, 0,1,2,3, 0,1,2, 0,1,0)
zl=xl+yl

TT=8
Xij.mat.cum=Xij.mat=matrix(0, TT, TT)
for(k in 1:length(Xij)){
  Xij.mat[xl[k],(yl[k]+1)]=Xij[k]
}
for(k in 1:TT){
Xij.mat.cum[k,]=cumsum(Xij.mat[k,])
}

Xij.mat.cum[Xij.mat==0]=0
f=c()
for(k in 1:(TT-1)){
  f[k]=sum(Xij.mat.cum[1:(TT-k),(k+1)])/sum(Xij.mat.cum[1:(TT-k),k])
  Xij.mat.cum[(TT-k+1):TT,(k+1)]=Xij.mat.cum[(TT-k+1):TT,k]*f[k]
}
rownames(Xij.mat)=c("2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018")
colnames(Xij.mat)=c("1","2","3","4", "5", "6", "7", "8")
```
```{r}
Xij.mat
```

##Model 1##
```{r, echo = FALSE}
TT=8
CL=glm(Xij~as.factor(xl)+ as.factor(yl), poisson(link=log) )
coefs=exp(coef(CL))

alpha.glm=coefs[1]*c(1, coefs[2:TT])
beta.glm=c(1, coefs[(TT+1):(2*TT-1)])

Xij.mat.glm=matrix(0,TT,TT)
A=exp(predict.glm(CL))
for(k in 1:length(Xij)){
  Xij.mat.glm[xl[k],(yl[k]+1)]=A[k]
}
CL_mat=Xij.mat
CL_mat.cum=Xij.mat.cum
CL_mat.cum[,1]=CL_mat[,1]
for(k in 2:(TT)){
  CL_mat[(TT-k+2):TT,k]=exp(predict.glm(CL,newdata=data.frame(xl=(TT-k+2):TT, yl=rep(k-1,k-1))))
  CL_mat.cum[,k]=CL_mat.cum[,(k-1)]+CL_mat[,k]
}
##Predicted Upper Triangle
Xij.mat.glm

##Payments
CL_mat.cum

##Combined Triangles
CL_mat
```