---
title: "MIdterm2 makeup"
author: "Curtis Thorson, curtist2"
date: "May 13, 2018"
output: html_document
---



```{r}
Data = read.csv("SingaporeAuto.csv")

Data$Female=1*(Data$SexInsured=="F")
Data$Auto=1*(Data$VehicleType=="A")
Data$NCD1F=relevel(factor(Data$NCD), ref="50")
I=(Data$AgeCat==0)
Data$AgeCat[I]=7

Data$AgeCatF=relevel(factor(Data$AgeCat), ref="7")
Data$VAgeCat1F=relevel(factor(Data$VAgecat1), ref="6")

Data_Auto=Data[Data$VehicleType=="A",]
Data_Other=Data[Data$VehicleType!="A",]
n_Auto=length(Data_Auto$Clm_Count)
n_Other=length(Data_Other$Clm_Count)

Nr_Acc_Auto=sum(Data_Auto$Clm_Count)
Nr_Acc_Other=sum(Data_Other$Clm_Count)

# Fit Poisson
CountGLM_P=glm(Clm_Count ~ Female + Auto  + Auto:AgeCatF + Auto:NCD1F + VAgeCat1F, offset=LNWEIGHT, poisson(link=log), data= Data)

# Fit negative binomial
MLE = function(Param, N, E){
  lambdaNB=Param[1]
  gammaNB=Param[2]
NB = -sum(log((gamma(N+gammaNB))/(gamma(gammaNB)*factorial(N))*((1-((lambdaNB*E)/(gammaNB+(lambdaNB*E))))^gammaNB)*(((lambdaNB*E)/(gammaNB+(lambdaNB*E)))^N)))
return(NB)
}
param_vector=c(1,1)
d=MLE(Param = param_vector, N=Data$Clm_Count, E=Data$Exp_weights)

est = optim(par=param_vector, fn=MLE, N=Data$Clm_Count, E=Data$Exp_weights)
est

est_lambda = est$par[1]
est_gamma = est$par[2]
```

```{r}
# Check Min/Max
z=matrix(data=NA , nrow=40, ncol=40)
x= seq(0.01, .4, 0.01)
  y= seq(0.04, 1.6, 0.04)
  nx=length(x)
ny=length(y)
for(i in 1:nx){
  for(k in 1:ny){
    vector=c(x[i],y[k])
    z[i,k]=MLE(Param = vector, N=Data$Clm_Count, E=Data$Exp_weights)
  }
}
persp(x,y,z,d=1.5)

```

```{r}
# Claim counts
NrClaims=unique(Data$Clm_Count) 
Claims=c()
nn=length(NrClaims)
for(i in 1:nn){
Claims[i]=sum(Data$Clm_Count==NrClaims[i])
}

# Fit Negative Binomial
NrClaims=unique(Data$Clm_Count)
Claims_NB=c()

E=Data$Exp_weights
for(i in 1:nn){
  N=NrClaims[i]
  Claims_NB[i]= sum((gamma(N+est_gamma))/(gamma(est_gamma)*factorial(N))*((1-((est_lambda*E)/(est_gamma+(est_lambda*E))))^est_gamma)*(((est_lambda*E)/(est_gamma+(est_lambda*E)))^N))
}



# Compare models
lambdaHat_GLM=exp(predict(CountGLM_P))

Claims=c()
Claims_Poisson_GLM=c()

for(i in 1:length(NrClaims)){
  k=NrClaims[i]
  Claims[i]=sum(Data$Clm_Count==NrClaims[i])

  Claims_Poisson_GLM[i]=sum(exp(-lambdaHat_GLM)*(lambdaHat_GLM)^k/factorial(k))
}
options(digits=2)
Table=matrix(c(NrClaims, Claims, Claims_NB, Claims_Poisson_GLM), length(Claims),4)
colnames(Table)=c("#Claims", "Data", "Negative Binomial", "Poisson Regression"  )
as.table(Table)

# Chi Square
ChiSqSt_NB=sum((Claims-Claims_NB)^2/Claims_NB)
ChiSqSt_NB

ChiSqST_Poisson=sum((Claims-Claims_Poisson_GLM)^2/Claims_Poisson_GLM)
ChiSqST_Poisson
```

\newcommand\given[1][]{\:#1\vert\:}


$$E[N] = E[E[N\given\theta]$$

$$= E[\lambda\theta]$$

$$= \lambda{E}[\theta]$$

$$= \lambda$$


$$Var[N] = Var[E[N\given\theta]] + E[Var[N\given\theta]]$$

$$= Var[E[\lambda\theta]] + E[Var[\lambda\theta]$$

$$= \lambda^2 Var[\theta] + E[\lambda]$$

$$= \lambda^2 1/\gamma + \lambda$$
$$= \lambda + (1 + \lambda/\gamma)$$